#!/usr/bin/env sh
# Run this script to deploy the app to Github Pages.

# Stash any changes
git stash --include-untracked

# Exit if any subcommand fails.
set -e

echo "Started deploying"

# Checkout build branch.
git branch -D build
git checkout -b build

# Build site.
npm run build

# Delete and move files.
find . -maxdepth 1 ! -name 'dist' ! -name '.git' ! -name '.gitignore' ! -name node-modules -exec rm -rf {} \;
mv dist/* .
rm -R dist/

# Push to build branch.
git add -fA
git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
git push -f -q origin build

# Move back to previous branch.
git checkout -
git stash pop

echo "Deployed Successfully!"

exit 0
